name: Secret Scan

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install
        run: |
          python -m pip install regex GitPython
      - name: Run secret scan
        run: |
          python -m gsa.cli --path . --out secret_report.json --history 20 || true
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: secret-report
          path: secret_report.json
